disabled = false
languageCode = "en"
languageName = "English"
weight = 1
title = "KeepItREAL Development Blog"

[params]
  displayName = "EN"
  isoCode = "en"
  rtl = false
  dateFormat = "2 January 2006"
  # logo = "img/logo.png"
  # secondaryLogo = "img/secondary-logo.png"
  # description = "Public blog created by Conor Weir and Andrew Brady following the development of the KeepItREAL Web Application"
  # copyright = "Copy, _right?_ :thinking_face:"

# [params.author]
#   name = "Conor Weir"
#   email = "conor.weir5@mail.dcu.ie"
#   image = "img/blowfish_logo.png"
#   imageQuality = 96
#   headline = "3rd Year DCU COMSCI Student"
#   bio = "A 3rd Year DCU COMSCI Student developing a fake-news detection web application alongside project partner Andrew Brady."
#   links = [
#     { email = "mailto:conor.weir5@mail.dcu.ie" },
#     { link = "https://link-to-some-website.com/" },
#   ]
